# Generated by Django 3.2.7 on 2021-10-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=8)),
                ('lastname', models.CharField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='EmailForm',
        ),
    ]
