# Generated by Django 3.2.7 on 2021-10-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendService', '0002_auto_20211006_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=50)),
                ('companyName', models.CharField(max_length=100)),
                ('aboutUsText', models.TextField(max_length=1500)),
                ('images', models.ImageField(upload_to='')),
                ('adress', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
