# Generated by Django 3.2.7 on 2021-10-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendService', '0003_customerdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdata',
            name='images',
        ),
        migrations.AddField(
            model_name='customerdata',
            name='image1',
            field=models.ImageField(default='bild1', upload_to='assets/images'),
        ),
        migrations.AddField(
            model_name='customerdata',
            name='image2',
            field=models.ImageField(default='bild2', upload_to='assets/images'),
        ),
        migrations.AddField(
            model_name='customerdata',
            name='image3',
            field=models.ImageField(default='bild3', upload_to='assets/images'),
        ),
    ]
