# Generated by Django 3.2.7 on 2021-10-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendService', '0004_auto_20211009_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='aboutUsText',
            field=models.CharField(max_length=1500),
        ),
    ]
