# Generated by Django 3.2.7 on 2021-10-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendService', '0005_alter_customerdata_aboutustext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='aboutUsText',
            field=models.TextField(max_length=500),
        ),
    ]
