# Generated by Django 3.2.7 on 2021-10-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendService', '0008_auto_20211014_1936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
