# Generated by Django 3.2.7 on 2021-10-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendService', '0009_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='template',
            field=models.CharField(default='', max_length=700),
        ),
    ]
