# Generated by Django 3.2.7 on 2021-10-19 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendService', '0010_customerdata_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateSelections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('t1', 'templateOne.html'), ('t2', 'templateTwo.html'), ('t3', 'templateThree.html')], max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendService.templateselections'),
        ),
    ]
