# Generated by Django 3.2.7 on 2021-10-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendService', '0011_auto_20211019_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='template',
            field=models.CharField(default='', max_length=700),
        ),
        migrations.DeleteModel(
            name='TemplateSelections',
        ),
    ]
