# Generated by Django 3.2.7 on 2021-10-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendService', '0012_auto_20211019_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
