# Generated by Django 3.2.7 on 2021-10-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendService', '0017_auto_20211020_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='template',
            field=models.CharField(max_length=200),
        ),
    ]
