# Generated by Django 3.2.7 on 2021-10-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendService', '0018_alter_customerdata_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='template',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
